### ISSUE TITLE
Browserify issue with dependency

### ISSUE THREAD

**Issue by RichardLitt** [1lobby/mailgun-js#61]
I'm trying to use mailgun-fs in a browserify environment, and I'm getting this issue:

```js
SyntaxError: Line 4: Unexpected token var while parsing /Users/richard/src/beagle/node_modules/mailgun-js/node_modules/proxy-agent/node_modules/pac-proxy-agent/node_modules/get-uri/node_modules/ftp/lib/connection.js while parsing file: /Users/richard/src/beagle/node_modules/mailgun-js/node_modules/proxy-agent/node_modules/pac-proxy-agent/node_modules/get-uri/node_modules/ftp/lib/connection.js
    at Stream.end (/Users/richard/src/beagle/node_modules/browserify/node_modules/insert-module-globals/index.js:73:21)
    at _end (/Users/richard/src/beagle/node_modules/browserify/node_modules/insert-module-globals/node_modules/through/index.js:65:9)
    at Stream.stream.end (/Users/richard/src/beagle/node_modules/browserify/node_modules/insert-module-globals/node_modules/through/index.js:74:5)
    at Transform.onend (/Users/richard/src/beagle/node_modules/browserify/node_modules/readable-stream/lib/_stream_readable.js:523:10)
    at Transform.g (events.js:199:16)
    at Transform.emit (events.js:129:20)
    at /Users/richard/src/beagle/node_modules/browserify/node_modules/readable-stream/lib/_stream_readable.js:965:16
    at process._tickCallback (node.js:355:11)
``` 
Anyone else seen this? mailgun-js v0.6.8

**Comment by RichardLitt** [comment]
Ah, the problem wasn't with mailgun-js. I've submitted a PR to node-ftp to enable brfs global transforms with fs, [here](https://github.com/mscdex/node-ftp/pull/108).
