### ISSUE TITLE
config important `true` error

### ISSUE THREAD

**Issue by minessis** [1lobby/mailgun-js#79]
when
```javascript
mailgun.messages().send(config, function (err, data) { 
  // do stuff with arguments 
});
```
such that `config.important` exists and is `true` and `config.attachment` exists and is `string` or `buffer`

yields the following error:
`_http_outgoing.js:433
    throw new TypeError('first argument must be a string or Buffer');
          ^
TypeError: first argument must be a string or Buffer
    at ClientRequest.OutgoingMessage.write (_http_outgoing.js:433:11)`

Very strange behavior, as this error is not thrown when `config.attachment` does not exist OR when `config.important` is removed, the attachment remains valid and is delivered as expected.

They do not co-exist well.

**Comment by anorsich** [comment]
I've stuck with completely same issue. Attachments work perfectly on node.js v0.10, but does not work on node.js v4+. Here is full stack trace:

```
_http_outgoing.js:426
    throw new TypeError('first argument must be a string or Buffer');
    ^

TypeError: first argument must be a string or Buffer
    at ClientRequest.OutgoingMessage.write (_http_outgoing.js:426:11)
    at FormData.ondata (stream.js:31:26)
    at emitOne (events.js:77:13)
    at FormData.emit (events.js:169:7)
    at FormData.CombinedStream.write (/Users/andrew/work/pestworks/pestworks-core/lib/node_modules/mailgun-js/node_modules/form-data/node_modules/combined-stream/lib/combined_stream.js:118:8)
    at FormData.CombinedStream._pipeNext (/Users/andrew/work/pestworks/pestworks-core/lib/node_modules/mailgun-js/node_modules/form-data/node_modules/combined-stream/lib/combined_stream.js:106:8)
    at FormData.CombinedStream._getNext (/Users/andrew/work/pestworks/pestworks-core/lib/node_modules/mailgun-js/node_modules/form-data/node_modules/combined-stream/lib/combined_stream.js:79:10)
    at FormData.CombinedStream._pipeNext (/Users/andrew/work/pestworks/pestworks-core/lib/node_modules/mailgun-js/node_modules/form-data/node_modules/combined-stream/lib/combined_stream.js:107:8)
    at FormData.CombinedStream._getNext (/Users/andrew/work/pestworks/pestworks-core/lib/node_modules/mailgun-js/node_modules/form-data/node_modules/combined-stream/lib/combined_stream.js:79:10)
    at FormData.CombinedStream._pipeNext (/Users/andrew/work/pestworks/pestworks-core/lib/node_modules/mailgun-js/node_modules/form-data/node_modules/combined-stream/lib/combined_stream.js:107:8)
    at FormData.<anonymous> (/Users/andrew/work/pestworks/pestworks-core/lib/node_modules/mailgun-js/node_modules/form-data/node_modules/combined-stream/lib/combined_stream.js:91:10)
    at FormData.<anonymous> (/Users/andrew/work/pestworks/pestworks-core/lib/node_modules/mailgun-js/node_modules/form-data/lib/form_data.js:178:5)
    at FormData.CombinedStream._getNext (/Users/andrew/work/pestworks/pestworks-core/lib/node_modules/mailgun-js/node_modules/form-data/node_modules/combined-stream/lib/combined_stream.js:84:3)
    at FormData.CombinedStream._pipeNext (/Users/andrew/work/pestworks/pestworks-core/lib/node_modules/mailgun-js/node_modules/form-data/node_modules/combined-stream/lib/combined_stream.js:107:8)
    at FormData.CombinedStream._getNext (/Users/andrew/work/pestworks/pestworks-core/lib/node_modules/mailgun-js/node_modules/form-data/node_modules/combined-stream/lib/combined_stream.js:79:10)
    at FormData.CombinedStream._pipeNext (/Users/andrew/work/pestworks/pestworks-core/lib/node_modules/mailgun-js/node_modules/form-data/node_modules/combined-stream/lib/combined_stream.js:107:8)
    at FormData.CombinedStream._getNext (/Users/andrew/work/pestworks/pestworks-core/lib/node_modules/mailgun-js/node_modules/form-data/node_modules/combined-stream/lib/combined_stream.js:79:10)
    at FormData.CombinedStream._pipeNext (/Users/andrew/work/pestworks/pestworks-core/lib/node_modules/mailgun-js/node_modules/form-data/node_modules/combined-stream/lib/combined_stream.js:107:8)
    at FormData.<anonymous> (/Users/andrew/work/pestworks/pestworks-core/lib/node_modules/mailgun-js/node_modules/form-data/node_modules/combined-stream/lib/combined_stream.js:91:10)
    at FormData.<anonymous> (/Users/andrew/work/pestworks/pestworks-core/lib/node_modules/mailgun-js/node_modules/form-data/lib/form_data.js:178:5)
    at FormData.CombinedStream._getNext (/Users/andrew/work/pestworks/pestworks-core/lib/node_modules/mailgun-js/node_modules/form-data/node_modules/combined-stream/lib/combined_stream.js:84:3)
    at FormData.CombinedStream._pipeNext (/Users/andrew/work/pestworks/pestworks-core/lib/node_modules/mailgun-js/node_modules/form-data/node_modules/combined-stream/lib/combined_stream.js:107:8)
```

P.S. I switched over to the [mailgun-es6](https://github.com/gpit2286/mailgun-es6), which works great so far and has zero dependencies.
